### PR TITLE
#155 - fix json body decode

### LINKED ISSUE #155: Returns 500 when creating an entity
Apitte returns a status code of 500 when attempting to create an entity from a request that is not valid.

The expected behavior is that it returns a status code of 400.

### PR DESCRIPTION
**Pull request by miranovy**
Apitte return status code 400 when request body is not valid json.

Closes #155

### CODE REVIEW

File: src/Mapping/Request/BasicEntity.php [hunk 1]
```diff
@@ -78,7 +80,13 @@ protected function normalize(string $property, $value)
 	 */
 	protected function fromBodyRequest(ApiRequest $request): self
 	{
-		return $this->factory((array) $request->getJsonBody(true));
+		try {
+			$body = (array) $request->getJsonBody(true);
+		} catch (JsonException $ex) {
+			throw new ClientErrorException('Invalid json data: ' . $ex->getMessage());
```
Comment (f3l1x) [inline src/Mapping/Request/BasicEntity.php:86]: What about `throw new ClientErrorException('Invalid json data', null, $e);`? To keep origin message.

Comment (miranovy) [reply src/Mapping/Request/BasicEntity.php]: Thank you for your comment, it is incorporated

**Comment by f3l1x** [comment]
Thank you
